@startuml
class Notification {
    + NotificationId : int <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Message : string <<get>> <<set>>
    + Notified : bool <<get>> <<set>> = false
    + NotifyUID : int <<get>> <<set>>
    + Notification()
    + Notification(title:string, message:string, notifyUID:int)
}
class NotificationService {
    + {static} GetNotificationsForUser(id:int, authToken:string) : List<Notification>
}
Notification o-> "MessageCreationTime" DateTime
@enduml
