@startuml
!include ./Frontend/Backend.puml
!include ./Frontend/JwtService.puml
!include ./Frontend/Authentication.puml
!include ./Frontend/Program.puml
!include ./Backend/IErfassung.puml
!include ./Backend/SIMSContext.puml
!include ./Backend/Program.puml
!include ./Authentication/Role.puml
!include ./Authentication/User.puml
!include ./Authentication/AuthContext.puml
!include ./Authentication/Authentication.puml
!include ./Authentication/Program.puml
!include ./Frontend/Classes/Notification.puml
!include ./Frontend/Classes/System.puml
!include ./Frontend/Classes/Issue.puml
!include ./Frontend/Classes/Employee.puml
!include ./Frontend/Extensions/RedisCache.puml
!include ./Frontend/Pages/Issues.cshtml.puml
!include ./Frontend/Pages/Employees.cshtml.puml
!include ./Frontend/Pages/dashboard.cshtml.puml
!include ./Frontend/Pages/defaultMode.cshtml.puml
!include ./Frontend/Pages/_AdminLte.cshtml.puml
!include ./Frontend/Pages/Systems.cshtml.puml
!include ./Frontend/Pages/Index.cshtml.puml
!include ./Backend/Classes/Notification.puml
!include ./Backend/Classes/Manufactor.puml
!include ./Backend/Classes/System.puml
!include ./Backend/Classes/Issue.puml
!include ./Backend/Classes/Logs.puml
!include ./Backend/Classes/Authentication.puml
!include ./Backend/Classes/Employee.puml
!include ./Backend/Controllers/NotificationController.puml
!include ./Backend/Controllers/IssueController.puml
!include ./Backend/Controllers/SystemController.puml
!include ./Backend/Controllers/LogController.puml
!include ./Backend/Controllers/EmployeeController.puml
!include ./Authentication/Controllers/UserController.puml
!include ./Authentication/Controllers/RoleController.puml
!include ./Authentication/Controllers/AuthController.puml
!include ./Frontend/obj/Release/net7.0/.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include ./Frontend/obj/Release/net7.0/SIMS_Frontend.AssemblyInfo.puml
!include ./Frontend/obj/Release/net7.0/SIMS_Frontend.GlobalUsings.g.puml
!include ./Frontend/obj/Release/net7.0/SIMS_Frontend.RazorAssemblyInfo.puml
!include ./Frontend/obj/Debug/net7.0/.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include ./Frontend/obj/Debug/net7.0/SIMS_Frontend.AssemblyInfo.puml
!include ./Frontend/obj/Debug/net7.0/SIMS_Frontend.GlobalUsings.g.puml
!include ./Frontend/obj/Debug/net7.0/SIMS_Frontend.RazorAssemblyInfo.puml
!include ./Backend/obj/Release/net7.0/.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include ./Backend/obj/Release/net7.0/SIMS_Backend.AssemblyInfo.puml
!include ./Backend/obj/Release/net7.0/SIMS_Backend.GlobalUsings.g.puml
!include ./Backend/obj/Debug/net8.0/SIMS_Backend.AssemblyInfo.puml
!include ./Backend/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./Backend/obj/Debug/net8.0/SIMS_Backend.GlobalUsings.g.puml
!include ./Backend/obj/Debug/net7.0/.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include ./Backend/obj/Debug/net7.0/SIMS_Backend.AssemblyInfo.puml
!include ./Backend/obj/Debug/net7.0/SIMS.AssemblyInfo.puml
!include ./Backend/obj/Debug/net7.0/SIMS.MvcApplicationPartsAssemblyInfo.puml
!include ./Backend/obj/Debug/net7.0/SIMS_Backend.GlobalUsings.g.puml
!include ./Backend/obj/Debug/net7.0/SIMS_Backend.MvcApplicationPartsAssemblyInfo.puml
!include ./Backend/obj/Debug/net7.0/SIMS.GlobalUsings.g.puml
!include ./Authentication/obj/Release/net7.0/.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include ./Authentication/obj/Release/net7.0/SIMS_Authentication.AssemblyInfo.puml
!include ./Authentication/obj/Release/net7.0/SIMS_Authentication.GlobalUsings.g.puml
!include ./Authentication/obj/Debug/net7.0/.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include ./Authentication/obj/Debug/net7.0/SIMS_Authentication.MvcApplicationPartsAssemblyInfo.puml
!include ./Authentication/obj/Debug/net7.0/SIMS_Authentication.AssemblyInfo.puml
!include ./Authentication/obj/Debug/net7.0/SIMS_Authentication.GlobalUsings.g.puml
@enduml
