@startuml
class IndexModel {
    + FailedLogin : bool <<get>> <<set>>
    + OnGet() : IActionResult
    + OnPost() : IActionResult
}
class UserModel {
    + Username : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
}
PageModel <|-- IndexModel
PageModel <|-- UserModel
@enduml
